# The URL the site will be built for
base_url = "https://andrealeopardi.com/"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

title = "Andrea Leopardi"
description = "Writing about Elixir, system architecture, and more."

## Feeds

# Generate main feed for pages with a date.
generate_feed = true

# The filename to use for the feed. Used as the template filename, too.
feed_filename = "feed.xml"

# The number of articles to include in the feed. All items are included if
# this limit is not set (the default).
feed_limit = 20

## Taxonomies

taxonomies = [{ name = "tags", feed = true }]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
highlight_theme = "css"
highlight_themes_css = [
    { theme = "ayu-dark", filename = "syntax-theme-dark.css" },
    { theme = "ayu-light", filename = "syntax-theme-light.css" },
]

[extra]
full_name = "Andrea Leopardi"
email = "hi@andrealeopardi.com"
twitter_username = "whatyouhide"
github_username = "whatyouhide"
talks_youtube_playlist_url = "https://youtube.com/playlist?list=PLd7I3U4fDsUJfNM-N7Kyss66gmml_OSDq"
